### ISSUE TITLE
About how to build dataset?

### ISSUE THREAD

**Issue by alice929** [joachimes/SceneGraphGeneration#1]
I want to know how to build dataset,could you tell me ? thanks

**Comment by joachimes** [comment]
The data is the same that was used in SceneGraphNet [[Zhou
et al. 2019]](https://arxiv.org/abs/1907.11308). They analysed the structure of all the 3D scenes
in the dataset SUNCG [[Song et al . 2017]](https://arxiv.org/abs/1611.08974). From the graph it is then
possible to reconstruct the scenes from the original dataset
SUNCG. The dataset SUNCG is no longer available online,
but the graph structure dataset used in SceneGraphNet is
still available at [this link](https://drive.google.com/file/d/11D2LFUcyzTPGPBhEbEq9-6-l71Rkco4D/view)
